### ISSUE TITLE
waves.cs missing float to int correction?

### ISSUE THREAD

**Issue by Sidremus** [ditzel/UnityOceanWavesAndShip#2]
In GetHeight(), when calculating `height`, the called function `index` is expecting an int but gets a float.
I'm new to this, but I think this should be different, right?

`//weighted sum
        var height = Mesh.vertices[index(p1.x, p1.z)].y * (max - Vector3.Distance(p1, localPos))
                   + Mesh.vertices[index(p2.x, p2.z)].y * (max - Vector3.Distance(p2, localPos))
                   + Mesh.vertices[index(p3.x, p3.z)].y * (max - Vector3.Distance(p3, localPos))
                   + Mesh.vertices[index(p4.x, p4.z)].y * (max - Vector3.Distance(p4, localPos));`

**Comment by Sidremus** [comment]
Ok, this is probably the least elegant way to fix the issue, but I did this:
`[index(Mathf.RoundToInt(p1.x), Mathf.RoundToInt(p1.z))]`

It's not ideal, but I'm not a programmer and didn't come up with anything else...

**Comment by ditzel** [comment]
This will do it for you. If you followed the tutorial point by point. x and z will already be an int
